services:
  - type: web
    name: yellow-card-model-epl
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SUPABASE_URL
        value: https://kijtxzvbvhgswpahmvua.supabase.co
      - key: SUPABASE_KEY
        value: sb_secret_8qWDEuaM0lh95i_CwBgl8A_MgxI1vQK

